server:
  port: 8040
  context-path: /
  maxPostSize: 0
spring:
  application.name: config-server
  profiles: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yufeicheng/springcloud_java
          search-paths: config-repo
          username: 873401580@qq.com
          password:
    bus:
      trace:
        enabled: true   #访问 /bus/refresh 后访问 /trace 获取信息

  rabbitmq:
      host: 127.0.0.1
      # port 对应的是 5672 不是web 管理的 15672 ,增加完角色后 权限的赋予
      port: 7002
      username: chengyufei
      password: chengyufei
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

#而当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现
spring.aop.proxy-target-class: true
#JACKSON
spring.jackson:
  date-format: "yyyy-MM-dd HH:mm:ss"
  default-property-inclusion: NON_NULL
  time-zone: GMT+8



---
spring:
  profiles:
    active: configserver